
SELECT * FROM dbo.[Sales-Report-CSV];
Select Distinct Channel
FROM dbo.[Sales-Report-CSV];
Select Distinct Channel, [Item Name], Quantity
FROM dbo.[Sales-Report-CSV];
--This Query is working
SELECT Channel, SUM(CAST(Quantity AS INT)) AS 'Items by Channel' 
FROM dbo.[Sales-Report-CSV]
GROUP BY Channel;
-- What is the total revenue generated by each sales channel?
SELECT Channel, SUM(CAST(Cost AS float)) AS 'Revenue' 
FROM dbo.[Sales-Report-CSV]
GROUP BY Channel;
--What is the average cost of each transaction across all sales channels?
Select AVG(CAST(Cost AS float)) AS 'AVERAGE REVENUE'
FROM dbo.[Sales-Report-CSV]
--What is the average cost of each transaction from each sales channels?
SELECT Channel, AVG(CAST(Cost AS float)) AS 'Revenue' 
FROM dbo.[Sales-Report-CSV]
GROUP BY Channel;
--Who are the top 10 customers in terms of total spending?
SELECT TOP 10 [Transaction ID], [Customer Email], SUM(CAST(Cost AS float)) AS 'Total Spending'
FROM dbo.[Sales-Report-CSV] 
GROUP BY [Transaction ID], [Customer Email] 
ORDER BY SUM(CAST(Cost AS float)) DESC;
DELETE FROM dbo.[Sales-Report-CSV] WHERE [Customer Email] IN (SELECT [Customer Email] FROM dbo.[Sales-Report-CSV] GROUP BY [Customer Email] HAVING COUNT(*) > 1);


